version: '3'

services:
  minecraft:
    build:
      context: ./docker/minecraft
      args:
        - MINECRAFT_VERSION=1.19.2
        - PAPER_MINOR_VERSION=271
    environment:
      - EULA=true
      - "WORLD_NAME=${WORLD_NAME:-default_world}"
      - "HEAP_INIT=${HEAP_INIT:-1024M}"
      - "HEAP_MAX=${HEAP_MAX:-1024M}"
    volumes:
      - ./worlds:/minecraft/worlds
    ports:
      - ${LISTEN_PORT:-25565}:25565
    tty: true
    stdin_open: true
    restart: unless-stopped
